apiVersion: v1
kind: Service
{{- with .Values.api }}
metadata:  
  name: {{ print .name | quote }}
spec:
  type: NodePort
  selector:    
    app: {{ .name }}
  ports:  
  - port: {{ .config.containerPort }}
    nodePort: {{ .config.nodePort }}
{{- end }}