---
{{ include "go-api.deployment" .Values.api }}
            - name: "APP_VERSION"
              value: {{ .Chart.AppVersion | quote }}
          volumeMounts:
            - mountPath: /app
              name: app-volume
      volumes:
        - name: app-volume
          hostPath:
            path: /app
            type: Directory
---
{{ include "go-api.deployment" .Values.mongo }}
