kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30007
    hostPort: 3000
  extraMounts:
  - hostPath: /Users/drew/testground/go-api
    containerPath: /app