common:
  goApiPort: &goApiPort 3000
  goApiName: &goApiName go-api
  dbPort: &dbPort 27017
  dbName: &dbName mongodb

api:
  name: *goApiName
  image:
    name: *goApiName
    tag: local
  config:
    containerPort: *goApiPort
    nodePort: 30007
    env:
      APP_PORT: *goApiPort
      APP_NAME: *goApiName
      DB_PORT: *dbPort
      DB_HOST: *dbName
      DB_DATABASE: main

mongo:
  name: *dbName
  image:
    name: mongo
    tag: '5.0'
  config:
    containerPort: *dbPort